name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run production

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v0.1.4  # Update to a valid version
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/Thirdapp/  # Adjusted for your EC2 path
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart nginx
